########################################################################

# avec sudo ansible-playbook -c local config.vm1.yml
---
- hosts: localhost
  tasks:
    # adresse IPv4 avec nmcli (CLI pour NetworkManager)
    - shell: nmcli connection del "Connexion filaire 1"
      ignore_errors: True # permet à ansible de continuer
    - shell: nmcli connection del "Connexion filaire 2"
      ignore_errors: True # permet à ansible de continuer
    - shell: nmcli connection del "ansible-eth1"
      ignore_errors: True # permet à ansible de continuer
    - shell: nmcli connection del "ansible-eth2"
      ignore_errors: True # permet à ansible de continuer
    - shell: nmcli connection add ifname eth1 con-name ansible-eth1 type ethernet ip4 172.16.2.186/28
    - shell: nmcli connection add ifname eth2 con-name ansible-eth2 type ethernet ip6 fc00:1234:2::36/64
	#LAN1-6    
	- shell: ip -6 route add fc00:1234:1::/64 via fc00:1234:2::26
	#LAN1
	#LAN2
	#LAN3

   
