########################################################################

# avec sudo ansible-playbook -c local config.vm1.yml
---
- hosts: localhost
  tasks:
    # adresse IPv4 avec nmcli (CLI pour NetworkManager)
    - shell: nmcli connection del "Connexion filaire 1"
      ignore_errors: True # permet à ansible de continuer
    - shell: nmcli connection del "Connexion filaire 2"
      ignore_errors: True # permet à ansible de continuer
    - shell: nmcli connection del "ansible-eth1"
      ignore_errors: True # permet à ansible de continuer
    - shell: nmcli connection del "ansible-eth2"
      ignore_errors: True # permet à ansible de continuer
    - shell: nmcli connection add ifname eth1 con-name ansible-eth1 type ethernet ip4 172.16.2.156/28
    - shell: nmcli connection add ifname eth2 con-name ansible-eth2 type ethernet ip6 fc00:1234:1::16/64
    - sysctl: name="net.ipv4.ip_forward" value=1 sysctl_set=yes state=present reload=yes #activation du routage
    - shell: ip -6 route add fc00:1234:2::/64 via fc00:1234:1::26 #LAN2-6
    - shell: ip route add 172.16.2.128/28 via 172.16.2.151 #LAN1
    - shell: xterm -hold -e "sudo /mnt/partage/C/tunnel64d /mnt/partage/C/configVM1-6" &
# - shell: ip route add 172.16.2.160/28 via 172.16.2.1 #LAN2  route appliquée dans conf_tun
# - shell: ip route add 172.16.2.176/28 via 172.16.2.1 #LAN4  route appliquée dans conf_tun
